version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 4videos
      MONGO_INITDB_ROOT_PASSWORD: yU1T55xcVR
    ports:
      - "27017:27017"


  app:
    depends_on:
      - mongo
    build: .
    environment:
      - spring.data.mongodb.uri=mongodb://4videos:yU1T55xcVR@mongo:27017/videos
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"

networks:
  my-networks:
    driver: bridge
